# Generated by Django 2.0rc1 on 2017-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('completed', models.BooleanField()),
                ('editing', models.BooleanField()),
            ],
        ),
    ]
